version: '3.9'
services:
  db:
    container_name: db_container17
    image: postgres:17
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - .:/var/lib/postgres/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db

networks:
  db:
    driver: bridge  