"""set default value

Revision ID: 0aa0669495f4
Revises: 1c9962126f80
Create Date: 2025-06-09 19:08:24.159174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa0669495f4'
down_revision: Union[str, None] = '1c9962126f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.alter_column('user', 'id', server_default=sa.text("gen_random_uuid()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'id', server_default=None)
    # ### end Alembic commands ###
