name: Automated tests

on: push

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    tests:
        name: PyTest
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:17
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
        env:
            db_host: postgres
            db_port: 5432
            db_user: postgres
            db_pass: postgres
            db_name: test_db
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                pip install poetry
                poetry config virtualenvs.create false
                poetry install --no-root --no-interaction
            - name: Run tests
              run: poetry run pytest
